        function algebraicDist = GetAlgebraicDist(points, centerPoint, radii)

            algebraicDist = ((points(:,1)-centerPoint(1))/radii(1)).^2 ...
                          + ((points(:,2)-centerPoint(2))/radii(2)).^2 ...
                          + ((points(:,3)-centerPoint(3))/radii(3)).^2;
            end